Resolved conflict with "name" parameter used by some RTM parameters (for example list and task creation). Previously attempt to use name argument resulted in things like
TypeError: _call_method_auth() got multiple values for keyword argument 'name'